[iOS]Fix runtime crash on iOS 8.x.
The changes from previous commit 'Fix NSLog() on iOS 10.' in CDVLogger.h,
refer symbols defined in libSystem.tbd (_os_log_default). In fact, these symbols
don't exist in the iOS 8.x SDK.
All Cordova 4.x Xcode template projects don't link by default to libSystem.tbd,
so in order to resolve the issue, we weak-link to libSystem.tbd. Notice that weak-linking
is important because the dynamic linker will set all missing library symbols to 'nil'.

Detailed error:
dyld: Symbol not found: __os_log_default
  Referenced from: /Users/tpopov/Library/Developer/CoreSimulator/Devices/3382AC4A-2E4B-402F-B5AD-3DC915B293C9/data/Containers/Bundle/Application/DFE7E999-8DCD-46E7-B71B-BD10A1F3F91A/Cordova500.app/Cordova500
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib
 in /Users/tpopov/Library/Developer/CoreSimulator/Devices/3382AC4A-2E4B-402F-B5AD-3DC915B293C9/data/Containers/Bundle/Application/DFE7E999-8DCD-46E7-B71B-BD10A1F3F91A/Cordova500.app/Cordova500